### PR TITLE
Court: prevents drafting without randomness seed

### LINKED ISSUE #15: Prevent drafts happening without a randomness seed
Right now, if the first draft of a term happens more than 256 blocks after the term starts, the blockhash that will be returned for the `randomnessBN` of the term will be 0.

Options to work around this problem:

- Treat this as a round being drafted in the wrong term and require rescheduling as in #14 
- Implement a secondary `heartbeat()` function (which can be called one block after the actual `heartbeat`) that stores the `randomness` for the term. The caller could get the current `dependingDrafts * heartbeatFee` that is being paid to the `heartbeat()` caller and pay heartbeat fees just from activation, updates and deactivation fees (#7)

### PR DESCRIPTION
**Pull request by bingen**
Drafting will have to wait for a later term where randomness seed is
available.

Closes #15.

### CODE REVIEW

File: test/court-batches.js [hunk 1]
```diff
@@ -237,6 +241,23 @@ contract('Court: Batches', ([ rich, governor, arbitrable, juror1, juror2, juror3
         assert.isTrue(termsPassed > 1, 'draft was not split')
       })
 
+
+      it('needs to wait until next term if randomness is missing', async () => {
+        let totalJurorsDrafted = 0
```
Comment (izqui) [inline test/court-batches.js]: We can clean up a bunch of unused variables in this test
